"""
Pydantic schemas for the FastAPI REST API.
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class ScanRequest(BaseModel):
    """Payload to initiate a scan request."""

    target: str = Field(..., description="File or directory path to scan.")
    severity: str = Field(
        "LOW", description="Minimum severity to include: INFO | LOW | MEDIUM | HIGH | CRITICAL"
    )
    format: str = Field("json", description="Output format: json | html | sarif")


class ScanAsyncResponse(BaseModel):
    """Response returned when an async scan starts."""

    task_id: str = Field(..., description="Unique identifier for the background scan task.")
    status: str = Field(..., description="Current task status (e.g. 'PENDING', 'RUNNING').")
    message: str = Field(..., description="Details about the task initialization.")


class TaskStatusResponse(BaseModel):
    """Response detailing status of a background scan task."""

    task_id: str = Field(..., description="The task identifier.")
    status: str = Field(..., description="Task status: PENDING | RUNNING | COMPLETED | FAILED")
    result: dict[str, Any] | None = Field(
        None, description="The scan report dictionary (if COMPLETED)."
    )
    error: str | None = Field(None, description="Error message if the task FAILED.")


class PatchRequest(BaseModel):
    """Payload to apply a security patch to a file."""

    file_path: str = Field(..., description="Absolute path of the target file to patch.")
    findings: list[dict[str, Any]] = Field(
        ..., description="List of Finding dictionary payloads to resolve."
    )


class PatchResponse(BaseModel):
    """Response returned after patch application attempt."""

    success: bool = Field(
        ..., description="True if the file was successfully patched and validated."
    )
    is_ai_patch: bool = Field(
        ..., description="True if the applied patch was generated by the AI model."
    )
    message: str = Field(..., description="Status message explaining patch resolution details.")
    patched_code: str | None = Field(None, description="The corrected source code (if successful).")


class DirectScanRequest(BaseModel):
    """Payload to scan raw code directly."""

    code: str = Field(..., description="Source code text to scan.")
    language: str = Field(..., description="Source code language (e.g. 'python', 'java').")
    file_path: str = Field(
        "app.py", description="Virtual filename/path label for finding location metadata."
    )
